#!/usr/bin/env python3

import tinys3
import json
from charmhelpers.core import hookenv

WORKSPACE = '/tmp/workspace'
S3_ACCESS_KEY = hookenv.action_get("s3-access-key")
S3_SECRET_KEY = hookenv.action_get("s3-secret-key")
BUCKET = hookenv.action_get("bucket")
ENDPOINT = hookenv.action_get("aws-endpoint")


def load_metadata():
    with open(''.join([WORKSPACE, "/.metadata"]), 'r') as f:
        metadata = json.load(f)

    return metadata


def upload_binary(metadata):
    hookenv.log('Uploading binary to s3://{}/{} to {}'.format(BUCKET, metadata['FileName'], ENDPOINT))
    conn = tinys3.Connection(S3_ACCESS_KEY, S3_SECRET_KEY, tls=True, endpoint=ENDPOINT)
    f = open(''.join([WORKSPACE, '/', metadata['FileName']]), 'rb')
    conn.upload(metadata['FileName'], f, BUCKET)


if __name__ == '__main__':
    hookenv.status_set('maintenance', 'Uploading binary')
    metadata = load_metadata()
    upload_binary(metadata)
    hookenv.status_set('active', 'Ready')
