#!/usr/bin/env python3
import os
import shutil
from git import Repo, Git
from charmhelpers.core import hookenv
from subprocess import check_call


WORKSPACE = '/tmp/workspace'
GOBBLIN_GIT = 'https://github.com/linkedin/gobblin.git'
RELEASE_TAG = 'gobblin_0.6.0'
HADDOP_VER = "2.7.1"

